/**
 * Created by Jebin for iLeaf Solutions Pvt.Ltd
 * on February 12, 2020
 * Action Types - differnt action types used.
 */

// app
export const APP_NETWORK_STATUS = 'APP_NETWORK_STATUS';
export const APP_LANGUAGE_CHANGE = 'APP_LANGUAGE_CHANGE';
export const APP_STORE_CODE_CHANGE = 'APP_STORE_CODE_CHANGE';
export const ORIENTATION_CHANGE = 'ORIENTATION_CHANGE';
export const UPDATE_STORES_INFO = 'UPDATE_STORES_INFO';
export const UPDATE_FILTER_DATAS = 'UPDATE_FILTER_DATAS';
export const APP_UPDATE_USER_INFO = 'APP_UPDATE_USER_INFO';
export const APP_UPDATE_CURRENCY = 'APP_UPDATE_CURRENCY';
export const UPDATE_DEVICE_TYPE = 'UPDATE_DEVICE_TYPE';
export const UPDATE_BIOMETRIC_AUTH = 'UPDATE_BIOMETRIC_AUTH';
export const UPDATE_HOME_BANNERS = 'UPDATE_HOME_BANNERS';
export const UPDATE_APP_LOGO = 'UPDATE_APP_LOGO';
export const UPDATE_APP_LOCALIZATION_STATUS = 'UPDATE_APP_LOCALIZATION_STATUS';

//loaders
export const ENABLE_LOADER = 'ENABLE_LOADER';
export const DISABLE_LOADER = 'DISABLE_LOADER';
export const ENABLE_SCREEN_LOADER = 'ENABLE_SCREEN_LOADER';
export const DISABLE_SCREEN_LOADER = 'DISABLE_SCREEN_LOADER';
export const PRODUCT_LIST_ENABLE_LOADER = 'PRODUCT_LIST_ENABLE_LOADER';
export const PRODUCT_LIST_DISABLE_LOADER = 'PRODUCT_LIST_DISABLE_LOADER';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const USER_DATA_REQUEST = 'USER_DATA_REQUEST';
export const RENEW_USER_TOKEN = 'RENEW_USER_TOKEN';
export const PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST';
export const PROFILE_UPDATE_RESPONSE = 'PROFILE_UPDATE_RESPONSE';
export const PASSWORD_UPDATE_REQUEST = 'PASSWORD_UPDATE_REQUEST';
export const PASSWORD_UPDATE_RESPONSE = 'PASSWORD_UPDATE_RESPONSE';
export const USER_WISHLIST_RESPONSE = 'USER_WISHLIST_RESPONSE';
export const REMOVE_WISHLIST_ITEM = 'REMOVE_WISHLIST_ITEM';
export const ADD_WISHLIST_ITEM = 'ADD_WISHLIST_ITEM';
export const USER_LOG_OUT = 'USER_LOG_OUT';
export const GUEST_CART_CLEAR = 'GUEST_CART_CLEAR';
export const UPDATE_GUEST_INFO = 'UPDATE_GUEST_INFO';
export const SUBMIT_CONTACT_US = 'SUBMIT_CONTACT_US';
export const SOCIAL_MEDIA_LOGIN_REQUEST = 'SOCIAL_MEDIA_LOGIN_REQUEST';
export const UPDATE_SOCIAL_MEDIA_LOGIN_STATUS =
  'UPDATE_SOCIAL_MEDIA_LOGIN_STATUS';
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_RESPONSE = 'FORGOT_PASSWORD_RESPONSE';
export const ADD_EMAIL_REMINDER = 'ADD_EMAIL_REMINDER';
export const GET_EMAIL_REMINDER = 'GET_EMAIL_REMINDER';
export const UPDATE_EMAIL_REMINDER_ARRAY = 'UPDATE_EMAIL_REMINDER_ARRAY';
export const DELETE_EMAIL_REMINDER = 'DELETE_EMAIL_REMINDER';

// guest
export const CREATE_GUEST_CART = 'CREATE_GUEST_CART';
export const UPDATE_GUEST_TOKEN = 'UPDATE_GUEST_TOKEN';
export const GUEST_ADD_TO_CART = 'GUEST_ADD_TO_CART';
export const CLEAR_QUOTE_ID = 'CLEAR_QUOTE_ID';
export const CHECK_GUEST_SESSION = 'CHECK_GUEST_SESSION';

// cart
export const UPDATE_CART_LIST = 'UPDATE_CART_LIST';
export const GET_AVAILABLE_ADD_ONS = 'GET_AVAILABLE_ADD_ONS';
export const UPDATE_AVAILABLE_BALLOONS = 'UPDATE_AVAILABLE_BALLOONS';
export const UPDATE_AVAILABLE_GIFT_WRAP = 'UPDATE_AVAILABLE_GIFT_WRAP';
export const ADD_ADD_ONS = 'ADD_ADD_ONS';
export const GET_MORE_ADD_ONS = 'GET_MORE_ADD_ONS';

// register
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_RESPONSE = 'REGISTER_RESPONSE';
export const REGISTER_FAILED = 'REGISTER_FAILED';

// country selection
export const GET_STORES = 'GET_STORES';
export const GET_STORES_VIEW = 'GET_STORES_VIEW';
export const GET_STORES_RESPONSE = 'GET_STORES_RESPONSE';

// search
export const SEARCH_TEXT_CHANGE = 'SEARCH_TEXT_CHANGE';
export const UPDATE_SEARCH_HISTORY = 'UPDATE_SEARCH_HISTORY';
export const UPDATE_SEARCH_RESULT = 'UPDATE_SEARCH_RESULT';
export const CLEAR_SEARCH_RESULT = 'CLEAR_SEARCH_RESULT';
export const GET_TOP_SEARCHES = 'GET_TOP_SEARCHES';
export const SEARCH_TEXT_CHANGE_RESULT = 'SEARCH_TEXT_CHANGE_RESULT';

// categories
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const GET_ALL_CATEGORIES_RESPONSE = 'GET_ALL_CATEGORIES_RESPONSE';
export const GET_ALL_CATEGORIES_FAILURE = 'GET_ALL_CATEGORIES_FAILURE';
export const GET_SUB_CATEGORY_LIST = 'GET_SUB_CATEGORY_LIST';

//add address
export const ADD_ADDRESS_REQUEST = 'ADD_ADDRESS_REQUEST';
export const ADD_ADDRESS_RESPONSE = 'ADD_ADDRESS_RESPONSE';
export const ADD_ADDRESS_FAILED = 'ADD_ADDRESS_FAILED';
export const GUEST_ADD_ADDRESS_REQUEST = 'GUEST_ADD_ADDRESS_REQUEST';
export const GUEST_EDIT_ADDRESS_REQUEST = 'GUEST_EDIT_ADDRESS_REQUEST';
export const GET_AVAILABLE_REGIONS = 'GET_AVAILABLE_REGIONS';

// edit address
export const EDIT_ADDRESS_REQUEST = 'EDIT_ADDRESS_REQUEST';
export const EDIT_ADDRESS_RESPONSE = 'EDIT_ADDRESS_RESPONSE';
export const EDIT_ADDRESS_FAILED = 'EDIT_ADDRESS_FAILED';
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const DELETE_ADDRESS = 'DELETE_ADDRESS';

// products
export const GET_PRODUCTS_LIST = 'GET_PRODUCTS_LIST';
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
export const GET_RELATED_PRODUCT_DETAIL = 'GET_RELATED_PRODUCT_DETAIL';
export const UPDATE_PRODUCTS_LIST = 'UPDATE_PRODUCTS_LIST';
export const UPDATE_PRODUCT_DETAIL = 'UPDATE_PRODUCT_DETAIL';
export const GET_ROTTATION_IMGAGES_ARRAY = 'GET_ROTTATION_IMGAGES_ARRAY';
export const ADD_RECENTLY_VIEWED = 'ADD_RECENTLY_VIEWED';
export const REMOVE_RECENTLY_VIEWED = 'REMOVE_RECENTLY_VIEWED';
export const NOTIFY_ME = 'NOTIFY_ME';
export const GET_PRODUCT_DETAIL_WITH_URL_KEY =
  'GET_PRODUCT_DETAIL_WITH_URL_KEY';
export const GET_BOUGHT_TOGETHER_PRODUCTS = 'GET_BOUGHT_TOGETHER_PRODUCTS';

//filter response
export const FILTER_REQUEST = 'FILTER_REQUEST';
export const FILTER_RESPONSE = 'FILTER_RESPONSE';
export const FILTER_FAILURE = 'FILTER_FAILURE';

//filter page
export const LOAD_FILTER_REQUEST = 'LOAD_FILTER_REQUEST';
export const LOAD_FILTER_RESPONSE = 'LOAD_FILTER_RESPONSE';
export const LOAD_FILTER_FAILURE = 'LOAD_FILTER_FAILURE';
export const UPDATE_SELECTED_FILTERS = 'UPDATE_SELECTED_FILTERS';
export const RESET_FILTER = 'RESET_FILTER';
export const RESET_FILTER_DATA = 'RESET_FILTER_DATA';

//home category list
export const GET_CATEGORY_PRODUCTS_LIST = 'GET_CATEGORY_PRODUCTS_LIST';
export const CLEAR_CATEGORY_PRODUCTS_LIST = 'CLEAR_CATEGORY_PRODUCTS_LIST';
export const UPDATE_CATEGORY_PRODUCTS_LIST = 'UPDATE_CATEGORY_PRODUCTS_LIST';

//category product list
// export const GET_CATEGORY_PRODUCTS_LIST_FROM_CATEGORY = 'GET_CATEGORY_PRODUCTS_LIST_FROM_CATEGORY';
export const CLEAR_CATEGORY_PRODUCTS_LIST_FROM_CATEGORY =
  'CLEAR_CATEGORY_PRODUCTS_LIST_FROM_CATEGORY';
export const UPDATE_CATEGORY_PRODUCTS_LIST_FROM_CATEGORY =
  'UPDATE_CATEGORY_PRODUCTS_LIST_FROM_CATEGORY';

//home page
export const GET_HOME_REQUEST = 'GET_HOME_REQUEST';
export const GET_HOME_ADD_REQUEST = 'GET_HOME_ADD_REQUEST';
export const GET_HOME_RESPONSE = 'GET_HOME_RESPONSE';
export const GET_HOME_ADD_RESPONSE = 'GET_HOME_ADD_RESPONSE';
export const GET_HOME_FAILED = 'GET_HOME_FAILED';
export const GET_PROMOTION_CATEGORIES = 'GET_PROMOTION_CATEGORIES';
export const GET_PROMOTION_PRODUCTS = 'GET_PROMOTION_PRODUCTS';
export const GET_STATUS_DATA = 'GET_STATUS_DATA';

//cart
export const GET_PRODUCTS_IN_CART = 'GET_PRODUCTS_IN_CART';
export const CART_PRODUCT_LIST = 'CART_PRODUCT_LIST';
export const GET_PRODUCTS_IN_CART_FAILED = 'GET_PRODUCTS_IN_CART_FAILED';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const ADD_CART_PRODUCT_TO_WISHLIST = 'ADD_CART_PRODUCT_TO_WISHLIST';
export const UPADTE_CART_ID = 'UPADTE_CART_ID';
export const ADD_PRODUCT_TO_CART_LOGGEDUSER = 'ADD_PRODUCT_TO_CART_LOGGEDUSER';
export const UPDATE_CART_PRODUCT_LIST = 'UPDATE_CART_PRODUCT_LIST';
export const UPDATE_GUEST_CART_PRODUCT_LIST = 'UPDATE_GUEST_CART_PRODUCT_LIST';
export const REMOVE_GUEST_CART = 'REMOVE_GUEST_CART';
export const REMOVE_USER_CART = 'REMOVE_USER_CART';
export const UPDATE_GUEST_CART = 'UPDATE_GUEST_CART';
export const UPDATE_USER_CART = 'UPDATE_USER_CART';
export const GET_TOTAL_CART_COST = 'GET_TOTAL_CART_COST';
export const GET_LOGGED_USER_CART_ID = 'GET_LOGGED_USER_CART_ID';
export const UPDATE_CART_DATE_TIME = 'UPDATE_CART_DATE_TIME';
export const UPDATE_CART_TOTALS = 'UPDATE_CART_TOTALS';
export const GET_RE_TRY_PAYMENT_URL = 'GET_RE_TRY_PAYMENT_URL';
export const PAYMENT_PLACE_ORDER_RETRY = 'PAYMENT_PLACE_ORDER_RETRY';
export const GET_RETRY_PAYMENT_OPTIONS = 'GET_RETRY_PAYMENT_OPTIONS';
export const ADD_EXTRA_PRODUCTS_TO_CART = 'ADD_EXTRA_PRODUCTS_TO_CART';
export const MY_FATOORAH_CREATE_SESSION = 'MY_FATOORAH_CREATE_SESSION';
export const MY_FATOORAH_PROCESS_SESSION = 'MY_FATOORAH_PROCESS_SESSION';
export const MY_FATOORAH_GET_PAYMENT_METHODS =
  'MY_FATOORAH_GET_PAYMENT_METHODS';

//checkout
export const SET_SHIPMENT_INFO = 'SET_SHIPMENT_INFO';
export const APPLY_VOUCHER_CODE = 'APPLY_VOUCHER_CODE';
export const GET_PAYMENT_AND_SHIPPING_METHODS =
  'GET_PAYMENT_AND_SHIPPING_METHODS';
export const SET_BILLING_ADDRESS = 'SET_BILLING_ADDRESS';
export const GET_DELIVERY_DATE = 'GET_DELIVERY_DATE';
export const REMOVE_VOUCHER_CODE = 'REMOVE_VOUCHER_CODE';
export const PLACE_ORDER_COD = 'PLACE_ORDER_COD';
export const GET_COLLECTION_METHODS = 'GET_COLLECTION_METHODS';
export const GET_PAYMENT_URL = 'GET_PAYMENT_URL';
export const PAYMENT_PLACE_ORDER = 'PAYMENT_PLACE_ORDER';
export const GET_PAYMENT_FAILED_INFO = 'GET_PAYMENT_FAILED_INFO';
export const UPDATE_DELIVERY_NOTE = 'UPDATE_DELIVERY_NOTE';
export const ADD_DELIVERY_NOTE = 'ADD_DELIVERY_NOTE';
export const RETAIN_CART = 'RETAIN_CART';

//Order History
export const GET_ORDER_HISTORY = 'GET_ORDER_HISTORY';
export const GET_ORDER_DETAIL = 'GET_ORDER_DETAIL';
export const ORDER_REFUND = 'ORDER_REFUND';
export const RE_ORDER_ITEMS = 'RE_ORDER_ITEMS';

export const GET_ORDER_TRACKING = 'GET_ORDER_TRACKING';

//Review
export const ADD_REVIEW = 'ADD_REVIEW';
export const GET_REVIEW = 'GET_REVIEW';
export const UPDATE_REVIEW = 'UPDATE_REVIEW';
