/**
 * Created by Jebin for iLeaf Solutions Pvt.Ltd
 * on February 12, 2020
 * API constants - API constants, url end points etc.
 */

import Constants from '../config/constants';

const ApiConstants = {
  BASE_URL: Constants.APP_BASE_URL,
  // API_GET_PRODUCTS: "/products",
  API_GET_PRODUCTS: '/productsearch',
  FILTER: '/getlayered',
  API_GET_ALL_ATTRIBUTES: '/getAllcustomoptions',
  API_GET_STORES: '/store/storeGroups',
  API_GET_STORES_VIEW: '/store/storeViews',
  API_STORE_CONFIGURATION: '/store/storeConfigs',
  API_GET_WISHLIST: '/wishlist/product',
  API_REMOVE_WISHLIST_ITEM: '/wishlist/remove',
  API_ADD_WISHLIST_ITEM: '/wishlist/add',
  API_GET_PRODUCTS_IN_CATEGORY: '/customproducts/searchCriteria',
  API_GUEST_CART: '/guest-carts',
  API_GUEST_ADD_TO_CART: '/guest-carts/57/items',
  API_USER_CART_ID: '/carts/mine',
  API_GET_LOGGED_USER_CART: '/carts/mine/items',
  API_PRODUCT_CART: '/carts/mine/items',
  API_PRODUCT_DETAIL: '/customproducts/sku',
  API_PRODUCT_DETAIL_URL_KEY: '/customproducts/urlkey',
  API_PRODUCT_360_IMAGES: '/360details/sku',
  API_PRODUCT_HISTORY: '/orders',
  API_PRDUCT_UPDATE_CART_LOGGED_USER: '/cart',
  API_DELETE_ADDRESS: '/deleteAddress',
  API_UPDATE_USER_TOKEN: '/resetCustomertoken',

  API_REGISTER_USER: '/customers',
  API_LOGIN: '/customerlogin', //"/integration/customer/token",
  API_SOCIAL_MEDIA_LOGIN: '/socialMedialogin',
  API_GET_USER_INFO: '/customers/me',
  API_GET_CATEGORIES: '/categories/all',
  API_HOME: '/custom/homepage',
  API_PASSWORD_CHANGE: '/customers/me/password',
  API_ADD_ADDRESS: '/customers/me',
  API_POST_REVIEW: '/reviews',
  API_GET_DELIVERY_DATE_AND_TIME: '/getDeliverydateandtime/',
  API_FORGOT_PASSWORD: '/customers/password',
  API_UPDATE_CART_ITEM_LOGGED_USER: '/updatewholecartitems',
  API_UPDATE_CART_ITEM_GUEST: '/updatewholeguestcartitems',
  API_GET_AVAILABLE_ADD_ONS: '/getAddonsCategory', //"/getAddons",
  API_ADD_ADD_ONS_LOGIN_USER: '/addAddonstocart',
  API_ADD_ADD_ONS_GUEST_USER: '/addAddonstocartguest',
  API_CONTACT_US: '/contactUs',
  API_GET_ENABLE_ADDS: '/getAds',
  API_RELATED_PRODUCT_DETAIL: '/relativeProducts',
  API_REMOVE_VOUCHER: '/carts/mine/coupons',
  API_PLACE_COD_ORDER: '/processcod', //"/carts/mine/order",
  API_PLACE_COD_ORDER_GUEST: '/processcodguest',
  API_GET_PAYMENT_COLLECTION_METHODS_LOGGED_USER:
    '/myfatoorah/collectTokenMethods',
  //"/myfatoorah/collectMethods",
  API_GET_PAYMENT_COLLECTION_METHODS_GUEST_USER:
    '/myfatoorah/collectTokenGuestMethods',
  // "/myfatoorah/collectGuestMethods",
  API_GET_PAYMENT_URL_LOGGED_USER: '/myfatoorah/initToken', //'/myfatoorah/createOrder',
  API_GET_RE_TRY_PAYMENT_URL_LOGGED_USER: '/myfatoorah/reProcessChecking',
  API_GET_PAYMENT_URL_GUEST_USER: '/myfatoorah/initGuestToken', //'/myfatoorah/createGuestOrder',
  API_PROCESS_PAYMENT_LOGGED_USER: '/myfatoorah/orderProcess',
  API_PROCESS_PAYMENT_GUEST_USER: '/myfatoorah/orderProcessGuest',
  API_ORDER_REFUND: '/refund',
  API_NOTIFY_ME: '/notifyme',
  TOP_SEARCHES: '/topsearch',
  API_ADD_EMAIL_REMINDER: '/addbirthdayremainder',
  API_GET_ALL_EMAIL_REMINDER: '/getremainders',
  API_DELETE_EMAIL_REMINDER: '/deleteremainder',
  API_RE_ORDER: '/reorder',
  API_PAYMENT_ERROR_INFO: '/myfatoorah/response',
  API_ADD_EMAIL_REMINDER_GUEST: '/addbirthdayremainderGuest',
  API_DELETE_FROM_CART_LOGGED_USER: '/deleteitem',
  API_DELETE_FROM_CART_GUEST_USER: '/deleteitemguest',
  API_GET_ALL_CITIES: '/getallcities',
  API_GET_ALL_REGIONS: '/getallregions',
  API_GET_PROMOTION_CATEGORIES: '/home/categories',
  API_GET_PROMOTION_PRODUCTS: '/home/products',
  API_GET_MORE_ADD_ONS: '/getAddonsProducts',
  API_PROCESS_PAYMENT_RETRY_LOGGED_USER: '/myfatoorah/reProcessOrder',
  API_GET_RETRY_PAYMENT_OPTIONS: '/myfatoorah/activemethods',
  API_PROCESS_PAYMENT_USER: '/myfatoorah/orderProcess',
  API_GET_STATUS_DATA: '/statusvideos',
  API_RETAIN_CART_LOGGED_USER: '/postorder',
  API_RETAIN_CART_GUEST_USER: '/postorderGuest',
  API_BOUGHT_TOGETHER_PRODUCTS: '/crosssellProducts',
  API_ADD_EXTRA_PRODUCTS_LOGGED_USER: '/addextraItems',
  API_ADD_EXTRA_PRODUCTS_GUEST_USER: '/addextraItemsGuest',
  API_GET_SUB_CATEGORIES: '/childcategories',
  API_PROCESS_ORDER_LOGGED_USER: '/myfatoorah/process',
  API_PROCESS_ORDER_LOGGED_GUEST: '/myfatoorah/processGuest',

  API_MY_FATOORAH_CREATE_GUEST_SESSION: '/myfatoorah/createguestSession',
  API_MY_FATOORAH_CREATE_LOGGEDIN_USER_SESSION: '/myfatoorah/createSession',
  API_MY_FATOORAH_PROCESS_GUEST_SESSION: '/myfatoorah/processguestSession',
  API_MY_FATOORAH_PROCESS_LOGGEDIN_USER_SESSION: '/myfatoorah/processSession',
  API_MY_FATOORAH_GET_PAYMENT_METHODS: '/myfatoorah/v4/collectMethods',
  API_GET_PAYMENT_URL_MY_FATOORAH: '/myfatoorah/createOrder',
  API_GET_PAYMENT_URL_MY_FATOORAH_GUEST: '/myfatoorah/createGuestOrder',
  API_MY_FATOORAH_GET_PAYMENT_METHODS_GUEST:
    '/myfatoorah/v4/collectGuestMethods',
  API_ORDER_TRACKING: '/orders/history',
};

export default ApiConstants;
