/**
 * Created by Jebin for iLeaf Solutions Pvt.Ltd
 * on February 12, 2020
 * Images - App config for images
 */

const images = {
  flags: {
    kuwait: require('../assets/flags/kuwait.png'),
    ksa: require('../assets/flags/ksa.png'),
    oman: require('../assets/flags/oman.png'),
    beharin: require('../assets/flags/beharin.png'),
    uae: require('../assets/flags/uae.png'),
    qatar: require('../assets/flags/qatar.png'),
    international: require('../assets/flags/international.png'),
    globe: require('../assets/flags/globe.png'),
    ukFlag: require('../assets/flags/UKFlag.png'),
  },
  check: {
    checkmark: require('../assets/check.png'),
  },
  androidMap: require('../assets/images/androidMap.png'),
  iOSMap: require('../assets/images/iOSMap.png'),
  logo: require('../assets/images/logo.png'),
  emptySearchResult: require('../assets/images/emptySearchResult.png'),
  emptyFilterResult: require('../assets/images/emptyFilterResult.png'),
  noWishlist: require('../assets/images/no_wishlist.png'),
  noProductFoundPlaceholder: require('../assets/images/noProductFoundPlaceholder.png'),
  edit: require('../assets/icons/edit.png'),
  google: require('../assets/icons/google2.png'),
  fb: require('../assets/icons/facebook2.png'),
  apple: require('../assets/icons/apple.png'),
  arrowRight: require('../assets/icons/arrow_right.png'),
  home: require('../assets/icons/TabIcons/home.png'),
  categories: require('../assets/icons/TabIcons/categories.png'),
  wishlist: require('../assets/icons/TabIcons/wishlist.png'),
  account: require('../assets/icons/TabIcons/account.png'),
  search: require('../assets/icons/search.png'),
  cart: require('../assets/icons/cart.png'),
  backButton: require('../assets/icons/backButton.png'),
  filter: require('../assets/icons/filter.png'),
  variants: require('../assets/icons/variants.png'),
  share: require('../assets/icons/share.png'),
  flag1: require('../assets/icons/flag1.png'),
  close: require('../assets/icons/close.png'),
  likeImage: require('../assets/icons/likeIcon.png'),
  image360: require('../assets/icons/image360.png'),
  phone: require('../assets/icons/phone.png'),
  watsapp: require('../assets/icons/whatsapp.png'),
  envelope: require('../assets/icons/envelope.png'),
  addressEmpty: require('../assets/images/emptyAddress.png'),
  message: require('../assets/icons/message.png'),
  tick: require('../assets/icons/tick.png'),
  bluetick: require('../assets/icons/bluetick.png'),
  whiteTick: require('../assets/icons/whiteTick.png'),
  refreshIcon: require('../assets/icons/refreshIcon.png'),
  likeButtonWithShade: require('../assets/icons/likeButtonWithShade.png'),
  unLikeImageWithShade: require('../assets/icons/unLikeImageWithShade.png'),
  addressLocation: require('../assets/icons/addressLocation.png'),
  addressPhone: require('../assets/icons/addressPhone.png'),
  addressUser: require('../assets/icons/addressUser.png'),
  lock: require('../assets/icons/lock.png'),
  mail: require('../assets/icons/mail.png'),
  notepad: require('../assets/icons/notepad.png'),
  comment: require('../assets/icons/comment.png'),
  events: require('../assets/icons/events.png'),
  cross: require('../assets/icons/cross.png'),
  checkbox: require('../assets/icons/o-check.png'),
  unCheckbox: require('../assets/icons/o-uncheck.png'),

  imgBalloon: require('../assets/icons/img_balloon.png'),
  imgGift: require('../assets/icons/img_gift.png'),
  addAddress: require('../assets/icons/addAddress.png'),

  placeHolderProduct: require('../assets/images/placeHolderProduct.png'),
  filterIcons: {
    check_tick: require('../assets/icons/check_box_white.png'),
    check_outline: require('../assets/icons/outline_check_box.png'),
    toggle_outline: require('../assets/icons/outline_toggle.png'),
    toggle_selected: require('../assets/icons/selected_toggle.png'),
    hair_image: require('../assets/icons/e.jpg'),
  },
  videoPlay: require('../assets/icons/videoPlay.png'),
  bookmark: require('../assets/icons/bookmark.png'),
  orderHistory: require('../assets/icons/order_history.png'),
  flag: require('../assets/icons/flag.png'),
  switchLanguage: require('../assets/icons/switch_language.png'),
  phoneSolid: require('../assets/icons/phone_solid.png'),
  alarm: require('../assets/icons/alarm.png'),
  logout: require('../assets/icons/logout.png'),

  minus: require('../assets/icons/minus.png'),
  plus: require('../assets/icons/plus.png'),
  radioChecked: require('../assets/icons/radioChecked2.png'),
  radioUnchecked: require('../assets/icons/radioUnchecked.png'),
  arrowSide: require('../assets/icons/arrow-side.png'),
  boySelected: require('../assets/images/boy.png'),
  girl: require('../assets/images/girl.png'),
  allGender: require('../assets/images/gender.png'),
  ckeckbox_dot: require('../assets/icons/checkbox1.png'),
  deliveryTruck: require('../assets/icons/delivery-truck.png'),
  checkboxTick: require('../assets/icons/check-box.png'),
  logo2: require('../assets/icons/logo2.png'),
  overview: require('../assets/icons/overview.png'),
  orderHistory: require('../assets/icons/orderHistory.png'),

  trackOrders: require('../assets/icons/track.png'),

  addressBook: require('../assets/icons/addressBook.png'),
  changePassword: require('../assets/icons/changePassword.png'),
  signOut: require('../assets/icons/signOut.png'),
  chatWithUs: require('../assets/icons/chatWithUs.png'),
  callUs: require('../assets/icons/callUs.png'),
  keepInTouch: require('../assets/icons/keepInTouch.png'),
  reachUs: require('../assets/icons/reachUs.png'),
  english: require('../assets/icons/english.png'),
  arabic: require('../assets/icons/arabic.png'),
  aboutUs: require('../assets/icons/aboutUs.png'),
  ourTerms: require('../assets/icons/ourTerms.png'),
  shipment: require('../assets/icons/shipment.png'),
  newsLetter: require('../assets/icons/newsLetter.png'),
  fingerPrint: require('../assets/icons/fingerPrint.png'),
  productCell1Frame: require('../assets/icons/productCell1Frame.png'),
  productTruck: require('../assets/icons/productTruck.png'),
  offerBox: require('../assets/icons/offerBox.png'),
  productColor: require('../assets/icons/productColor.png'),
  productSize: require('../assets/icons/productSize.png'),
  productShop: require('../assets/icons/productShop.png'),
  iconLockbg: require('../assets/icons/iconLockbg.png'),
  iconLock: require('../assets/icons/iconLock.png'),
  success: require('../assets/icons/success.png'),
  editIcon: require('../assets/icons/editIcon.png'),
  giftWrapper: require('../assets/icons/giftWrapper.png'),
  productDetailMinus: require('../assets/icons/productDetailMinus.png'),
  productDetailPlus: require('../assets/icons/productDetailPlus.png'),
  upArrow: require('../assets/icons/upArrow.png'),
  male: require('../assets/icons/male.png'),
  female: require('../assets/icons/female.png'),
  radioChecked3: require('../assets/icons/radioChecked3.png'),
  radioUnchecked3: require('../assets/icons/radioUnchecked3.png'),
  appleIcon: require('../assets/icons/appleIcon.png'),
  plus2: require('../assets/icons/plus2.png'),
  arrowUp: require('../assets/icons/arrowUp.png'),
  arrowDown: require('../assets/icons/arrowDown.png'),
  fingerPrintAuth: require('../assets/icons/fingerPrintAuth.png'),
  addressRemove: require('../assets/icons/addressRemove.png'),
  increment: require('../assets/icons/increment.png'),
  decrement: require('../assets/icons/decrement.png'),
  map: require('../assets/icons/map.png'),
  loadingImage: require('../assets/images/loadingImage.gif'),

  bluebg: require('../assets/icons/bluebg.png'),

  popUpButtonWhatsApp: require('../assets/icons/popUpButtonWhatsApp.png'),
  popUpButtonMessage: require('../assets/icons/popUpButtonMessage.png'),
  popUpButtonCall: require('../assets/icons/popUpButtonCall.png'),
  popUoClose: require('../assets/icons/popUoClose.png'),
  radioUnchecked2: require('../assets/icons/radioUnchecked2.png'),
  lockmain: require('../assets/icons/lockmain.png'),
  closeCircle: require('../assets/icons/closeCircle.png'),
  adImage: require('../assets/icons/adImage.png'),
  boy: require('../assets/icons/boy.png'),
  girl: require('../assets/icons/girl.png'),
  profileEdit: require('../assets/icons/profileEdit.png'),
  privacyPolicy: require('../assets/icons/privacyPolicy.png'),
  FAQ: require('../assets/icons/FAQ.png'),
  floatButton: require('../assets/icons/floatButton.png'),
  productTruck2: require('../assets/icons/productTruck2.png'),
  addToCartPlus: require('../assets/icons/addToCartPlus.png'),
  filterGenderAll: require('../assets/icons/filterGenderAll.png'),
  girl_infant: require('../assets/icons/girl_infant.png'),
  girl_3_6: require('../assets/icons/girl_3_6.png'),
  girl_7_10: require('../assets/icons/girl_7_10.png'),
  girl_11_13: require('../assets/icons/girl_11_13.png'),
  girl_13_plus: require('../assets/icons/girl_13_plus.png'),
  boy_infant: require('../assets/icons/boy_infant.png'),
  boy_3_6: require('../assets/icons/boy_3_6.png'),
  boy_7_10: require('../assets/icons/boy_7_10.png'),
  boy_11_13: require('../assets/icons/boy_11_13.png'),
  boy_13_plus: require('../assets/icons/boy_13_plus.png'),

  uniSex_infant: require('../assets/icons/uniSex_infant.png'),
  uniSex_3_6: require('../assets/icons/uniSex_3_6.png'),
  uniSex_7_10: require('../assets/icons/uniSex_7_10.png'),
  uniSex_11_13: require('../assets/icons/uniSex_11_13.png'),
  uniSex_13_plus: require('../assets/icons/uniSex_13_plus.png'),

  searchNew: require('../assets/icons/searchNew.png'),
  homeCheckoutScreen: require('../assets/icons/home.png'),
  calender: require('../assets/icons/calendar.png'),
  cartEmpty: require('../assets/icons/cartEmpty.png'),
  NetworkError: require('../assets/icons/NetworkError.png'),
  emptyProduct: require('../assets/icons/emptyProduct.png'),
  apiError: require('../assets/icons/apiError.png'),
  modalClose: require('../assets/icons/modalClose.png'),
  trash: require('../assets/icons/trash.png'),
  cod: require('../assets/icons/cod.png'),
  facebook: require('../assets/icons/facebook_2.png'),
  twitter: require('../assets/icons/twitter.png'),
  googlePlus: require('../assets/icons/google-plus.png'),
  pinterest: require('../assets/icons/pinterest.png'),
  instagram: require('../assets/icons/instagram.png'),
  cat_def: require('../assets/icons/cat_def.png'),
  cat_def_small: require('../assets/icons/cat_def_small.png'),
  playIcon: require('../assets/icons/playIcon.png'),
  homeVideo: require('../assets/icons/homeVideo.png'),

  profile_facebook: require('../assets/icons/profile_facebook.png'),
  profile_apple: require('../assets/icons/profile_apple.png'),
  profile_google: require('../assets/icons/profile_google.png'),
  tickCheck: require('../assets/icons/tickCheck.png'),
  whatsapp: require('../assets/icons/wtsap.png'),
  categoriesNew: require('../assets/icons/TabIcons/categoriesNew.png'),
  myFathoraIcon: require('../assets/icons/myFathoraIcon.png'),
  homeAddress: require('../assets/icons/homeNew.png'),

  blueRadioChecked: require('../assets/icons/blueRadioChecked.png'),
  blueRadioUnChecked: require('../assets/icons/blueRadioUnchecked.png'),
  greyBack: require('../assets/icons/back.png'),
  homeIcon: require('../assets/icons/homeIcon.png'),

};

export default images; 
