import constants from '../../config/constants';
import Constants from '../../config/constants';
import {normalizedWidth, normalizedHeight} from '../../config/common';

const {StyleSheet} = require('react-native');

const styles = StyleSheet.create({
  cardWrap: {
    marginHorizontal: 1,
    // paddingBottom: 15.5,
    // borderBottomWidth: 0.25,
    borderBottomColor: constants.APP_GRAY_COLOR4,
    flexDirection: 'row',
  },
  productImg: {
    height: '100%',
    width: '100%',
    resizeMode: 'contain',
  },
  productImgWrap: {
    borderRadius: 5,
    height: 140,
    width: 100,
    justifyContent: 'center',
    borderWidth: 0.25,
    borderColor: constants.APP_GRAY_COLOR4,
    backgroundColor: constants.APP_WHITE_COLOR,
    // shadowColor: "#000",
    padding: 10,
    // shadowOffset: {
    //   width: 0,
    //   height: 1,
    // },
    // shadowOpacity: 0.22,
    // shadowRadius: 2.22,
    marginLeft: 10,
    // elevation: 5,
  },
  content: {
    paddingLeft: 20,
    flex: 1,
  },
  title: {
    color: constants.APP_BLACK_COLOR,
    fontSize: 14,
    fontFamily: constants.Fonts.BOLD,
    textAlign: 'left',
  },
  description: {
    fontSize: 12,
    color: constants.APP_GRAY_COLOR,
    fontFamily: constants.Fonts.REGULAR,
    paddingTop: 10,
  },
  bottomButtonContainer: {
    flexDirection: 'row',
    marginVertical: 15, 
    marginHorizontal: 15,  
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomButton1Container: { 
    flex:1, 
    justifyContent: "center",
    borderRadius: 10,
    borderColor: constants.APP_GRAY_COLOR4,
    backgroundColor: constants.APP_WHITE_COLOR,
    borderWidth: 0.5,   
    height: 40,
    
  },
  bottomButtonText: {
    fontFamily: constants.Fonts.MEDIUM,
    fontSize: 12,
    color: 'rgb(219, 71, 61)',
    paddingVertical: 10,
    textAlign: 'center',
  },
  bottomButtonText2: {
    fontFamily: constants.Fonts.MEDIUM,
    fontSize: 12,
    color: 'rgb(20, 68, 147)',
    paddingVertical: 10,
    textAlign: 'center',
  },
  row: {
    // paddingTop: 10,
  },
  row1: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    // paddingTop: 10,
    flex: 1,
  },
  row2: {
    flexDirection: 'row',
    // position:"absolute"
    // alignItems: "center",
    // flexWrap: "wrap",
    // paddingTop: 10,
  },
  specText: {
    fontSize: 12,
    color: constants.APP_GRAY_COLOR,
    fontFamily: constants.Fonts.REGULAR,
    paddingRight: 7,
    paddingTop: 10,
    textAlign: 'left',
  },
  unCheckboxImg: {
    height: 18,
    width: 18,
    // marginRight: 20,
    borderWidth: 1,
    borderColor: constants.APP_BLACK_COLOR,
  },
  checkboxImg: {
    height: 18,
    width: 18,
    // marginRight: 20,
    borderWidth: 1,
    borderColor: 'rgb(68,200,86)',
    alignItems: 'center',
    justifyContent: 'center',
    // tintColor: "#44c856",
  },
  checkBoxWrap: {
    width: '50%',
    // marginRight: 38,
    // flexDirection: 'row',
    alignItems: 'center',
    // flexWrap: 'wrap',
    paddingTop: 20,
    alignSelf: 'center',
    paddingHorizontal: 10,
  },
  semiBoldText: {
    fontSize: 11,
    color: constants.APP_GRAY_COLOR,
    fontFamily: constants.Fonts.MEDIUM,
  },
  checkBoxWrap1: {
    width: '50%',
    // marginRight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    // flexWrap: 'wrap',
    // paddingTop: 10,
    // backgroundColor: 'red',
    justifyContent: 'center',
  },
  semiBoldText1: {
    fontSize: 11,
    color: 'rgb(154,154,154)',
    fontFamily: constants.Fonts.MEDIUM,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 13,
  },
  priceWrap: {
    flexDirection: 'row',
  },
  priceRedText: {
    color: constants.APP_BLACK_COLOR,
    fontSize: 14,
    fontFamily: constants.Fonts.BOLD,
  },
  btnText: {
    color: constants.APP_GRAY_COLOR,
    fontFamily: constants.Fonts.REGULAR,
    fontSize: 10,
    textAlign: 'center',
  },
  greyBtn: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: constants.APP_GRAY_COLOR4,
    marginRight: 17,
    marginTop: 2,
    width: normalizedWidth(103),
    height: normalizedHeight(45),
    justifyContent: 'center',
    alignItems: 'center',
  },
  plusIcon: {
    height: 24,
    width: 24,
    resizeMode: 'contain',
  },
  increamentWrap: {
    flexDirection: 'row',
    marginTop: 10,
    alignItems: 'center',
  },
  count: {
    color: constants.APP_BLACK_COLOR,
    fontSize: 11,
    fontFamily: constants.Fonts.BOLD,
  },
  countNum: {
    marginHorizontal: 10,
    width: 30,
    textAlign: 'center',
    paddingVertical: 0,
    fontSize: 11,
    fontFamily: constants.Fonts.MEDIUM,
    color: constants.APP_BLACK_COLOR,
  },
  discountContainer: {
    // width: 50,
    // height: 15,
    // backgroundColor: 'rgb(169,0,23)',
    height: 20,
    width: 48,
    backgroundColor: 'rgb(139,197,81)',
    position: 'absolute',
    bottom: 5,
    left: 10,
    alignItems: 'center',
    justifyContent: 'center',
    // borderRadius: 4,
  },
  discountText: {
    color: constants.APP_WHITE_COLOR,
    // fontFamily: constants.Fonts.MYRIAD,
    fontFamily: constants.Fonts.REGULAR,
    fontSize: 9,
  },
  outOfStockContainer: {
    width: '100%',
    // height: 35,
    backgroundColor: 'rgba(249,249,249,1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  outOfStockText: {
    color: 'rgb(181,24,24)',
    fontSize: 16,
    fontFamily: Constants.Fonts.MEDIUM,
    textAlign: 'center',
    textAlignVertical: 'center',
    alignSelf: 'center',
    backgroundColor: 'rgba(249,249,249,1)',
    width: '100%',
  },
  overlay: {
    backgroundColor: 'rgba(255,255,255, 0.7)',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    elevation: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export default styles;
