import { StyleSheet } from "react-native";
import { normalizedHeight, normalizedWidth } from "../../config/common";
import constants from "../../config/constants";
// import constants from "../../config/constants";

const styles = StyleSheet.create({
  scrollView: {
    paddingTop: 15,
    flex: 1,
  },
  cardWrap: {
    marginHorizontal: 15,
    paddingBottom: 15.5,
    marginBottom: 19.5,
    borderBottomWidth: 0.5,
    borderBottomColor: constants.APP_GRAY_COLOR4,
    flexDirection: "row",
  },
  productImg: {
    height: "100%",
    width: "100%",
    resizeMode: "contain",
  },
  productImgWrap: {
    borderRadius: 10,
    height: 117,
    width: 88,
    justifyContent: "center",
    borderWidth: 0.25,
    borderColor: constants.APP_GRAY_COLOR4,
    backgroundColor: constants.APP_WHITE_COLOR,
    shadowColor: "#000",
    padding: 10,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,

    elevation: 5,
  },
  content: {
    paddingLeft: 20,
    flex: 1,
  },
  title: {
    color: constants.APP_BLACK_COLOR,
    fontSize: 14,
    fontFamily: constants.Fonts.BOLD,
    textAlign: "left",
  },
  description: {
    fontSize: 12,
    color: constants.APP_GRAY_COLOR3,
    fontFamily: constants.Fonts.REGULAR,
    paddingTop: 10,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    paddingTop: 10,
  },
  specText: {
    fontSize: 12,
    color: constants.APP_GRAY_COLOR3,
    fontFamily: constants.Fonts.REGULAR,
    paddingRight: 18,
  },
  unCheckboxImg: {
    height: 10,
    width: 10,
    marginRight: 10,
    tintColor: constants.APP_GRAY_COLOR3,
  },
  checkboxImg: {
    height: 10,
    width: 10,
    marginRight: 10,
    tintColor: "#44c856",
  },
  checkBoxWrap: {
    marginRight: 38,
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    paddingTop: 10,
  },
  semiBoldText: {
    fontSize: 11,
    color: constants.APP_GRAY_COLOR3,
    fontFamily: constants.Fonts.MEDIUM,
  },
  priceRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 13,
  },
  priceWrap: {
    flexDirection: "row",
  },
  priceRedText: {
    color: constants.APP_RED_COLOR,
    fontSize: 15,
    fontFamily: constants.Fonts.BOLD,
  },
  btnText: {
    color: constants.APP_GRAY_COLOR3,
    fontFamily: constants.Fonts.REGULAR,
    fontSize: 10,
    textAlign: "center",
  },
  greyBtn: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: constants.APP_GRAY_COLOR,
    marginRight: 17,
    marginTop: 2,
    width: normalizedWidth(103),
    height: normalizedHeight(29),
    justifyContent: "center",
  },
  plusIcon: {
    height: 24,
    width: 24,
    resizeMode: "contain",
  },
  increamentWrap: {
    flexDirection: "row",
    marginTop: 10,
    alignItems: "center",
  },
  count: {
    color: constants.APP_BLACK_COLOR,
    fontSize: 11,
    fontFamily: constants.Fonts.BOLD,
  },
  titleStyle: {
    textAlign: "left",
    marginTop: 10,
    marginLeft: 20,
    fontSize: 18,
    color: constants.APP_THEME_COLOR,
    fontFamily: constants.Fonts.MEDIUM,
  },
  // voucherInput: {
  //   width: normalizedWidth(289),
  //   height: 42,
  //   borderColor: constants.APP_GRAY_COLOR4,
  //   borderWidth: 0.5,
  //   borderRadius: 10,
  //   padding: 10,
  //   backgroundColor: "#f1f1f1",
  //   color: "rgb(117,117,117)",
  //   fontSize: 12,
  //   fontFamily: constants.Fonts.REGULAR,
  // },
  voucherInput: {
    flex: 1,
    fontSize: 13,
    fontFamily: constants.Fonts.REGULAR,
    color: "rgb(105, 113, 128)",
    height: 42,
    borderRadius: 5,
    paddingLeft: 10,
    backgroundColor: "rgb(247,248,250)",
    borderWidth: 1,
    borderColor: "rgb(217,217,217)",
  },
  orangeBtn: {
    backgroundColor: constants.APP_THEME_COLOR,
    height: 42,
    width: normalizedWidth(77),
    justifyContent: "center",
    borderRadius: 10,
    marginLeft: 11,
  },
  orangeBtnText: {
    color: constants.APP_WHITE_COLOR,
    fontSize: 12,
    textAlign: "center",
    fontFamily: constants.Fonts.MEDIUM,
  },
  voucherWrap: {
    marginHorizontal: 15,
    marginBottom: 20,
    paddingBottom: 21.5,
    borderBottomWidth: 0.5,
    borderBottomColor: constants.APP_GRAY_COLOR4,
  },
  TotalWrap: {
    marginHorizontal: 15,
    marginTop: 10,
    marginBottom: 10,
    borderBottomWidth: 0.5,
    borderBottomColor: constants.APP_GRAY_COLOR4,
  },
  itemWrap: {
    marginHorizontal: 15,   
    marginBottom: 5,   
  },
  horizontalLineWrap: {   
    marginBottom: 10,
    borderBottomWidth: 0.5,
    borderBottomColor: constants.APP_GRAY_COLOR4,
  },
  TotalRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  TotalLabel: {
    fontSize: 14,
    fontFamily: constants.Fonts.REGULAR,
    color: constants.APP_GRAY_COLOR5,
    lineHeight: 20,
    marginBottom: 13,
  },
  TotalLabelBold: {
    fontSize: 14,
    fontFamily: constants.Fonts.BOLD,
    color: "rgb(40, 48, 63)",
    lineHeight: 20,
    marginBottom: 13,
  },
  TotalValues: {
    fontSize: 14,
    fontFamily: constants.Fonts.MEDIUM,
    color: constants.APP_GRAY_COLOR5,
    lineHeight: 20,
    marginBottom: 13,
    textAlign: "left",
  },
  TotalValuesBold: {
    fontSize: 14,
    fontFamily: constants.Fonts.BOLD,
    color: "rgb(40, 48, 63)",
    lineHeight: 20,
    marginBottom: 13,
  },
  TotalValuesRed: {
    fontSize: 14,
    fontFamily: constants.Fonts.MEDIUM,
    color: constants.APP_RED_COLOR,
    lineHeight: 20,
    marginBottom: 13,
  },
  removeWrap: {
    backgroundColor: constants.APP_RED_COLOR,
    height: normalizedHeight(17),
    width: normalizedWidth(74),
    justifyContent: "center",
    // padding: 10,
    height: 17,
    borderRadius: 2,
    marginLeft: 20,
  },
  removeText: {
    textAlign: "center",
    color: constants.APP_WHITE_COLOR,
    fontFamily: constants.Fonts.REGULAR,
    fontSize: 10,
  },
  simpleRow: {
    flexDirection: "row",
  },
  itemCellContainer: {
    marginTop: 5,
    backgroundColor: constants.APP_WHITE_COLOR,
    borderBottomColor: constants.APP_SEPARATOR_COLOR,
    borderBottomWidth: 1,
    flex: 1,
  },
  removeVoucher: {
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  applyText: {
    fontSize: 13,
    fontFamily: constants.Fonts.MEDIUM,
    color: constants.APP_WHITE_COLOR,
  },
  applyButton: {
    width: normalizedWidth(83),
    height: 42,
    backgroundColor: constants.APP_THEME_COLOR,
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 10,
  },
});

export default styles;
