import { StyleSheet } from "react-native";
import AppStyles from "../../config/styles";
import Constants from "../../config/constants";
import { normalizedHeight, normalizedWidth } from "../../config/common";

const styles = StyleSheet.create({
  safeContainer: {
    flex: 1,
    backgroundColor: Constants.APP_WHITE_COLOR,
  },
  scrollContainer: {
    // marginTop: 5,
  },
  itemImage: {
    width: 14,
    height: 14,
    // marginEnd: 18,
    alignSelf: "center",
  },
  underLineStyle2: {
    borderBottomWidth: 1,
    borderBottomColor: Constants.APP_SEPARATOR_COLOR,
    marginTop: 18,
    marginBottom: 3,
    marginHorizontal: 18,
  },
  orderConfirmationText: {
    fontSize: 20,
    marginTop: 12,
    color: "rgb(46,199,107)",
    fontFamily: Constants.Fonts.REGULAR,
    textAlign: "left",
  },
  orderConfirmationSubText: {
    fontSize: 16,
    marginVertical: 10,
    color: "rgb(120,120,120)",
    fontFamily: Constants.Fonts.REGULAR,
    textAlign: "left",
  },
  deliveryStatusText: {
    fontSize: 14,
    marginVertical: 5,
    fontFamily: Constants.Fonts.REGULAR,
    textAlign: "left",
  },
  normalText: {
    fontSize: 14,
    fontFamily: Constants.Fonts.REGULAR,
    color: Constants.APP_GRAY_COLOR3,
    textAlign: "left",
  },
  textBlue: {
    fontSize: 14,
    fontFamily: Constants.Fonts.MEDIUM,
    color: "rgb(92,115,207)",
    textAlign: "left",
  },
  normalTextBold: {
    fontSize: 14,
    fontFamily: Constants.Fonts.BOLD,
    color: "rgb(0,0,0)",
    textAlign: "left",
  },
  largeTextBold: {
    fontSize: 15,
    marginTop: 4,
    fontFamily: Constants.Fonts.MEDIUM,
    color: "rgb(0,0,0)",
    textAlign: "left",
  },
  wrapper: {
    flexDirection: "row",
    marginHorizontal: 18,
    marginTop: 5,
    justifyContent: "space-between",
  },
  wrapperColumn: {
    marginHorizontal: 20,
  },
  addressText: {
    fontSize: 14,
    marginTop: 7,
    marginBottom: 12,
    fontFamily: Constants.Fonts.REGULAR,
    color: Constants.APP_GRAY_COLOR3,
    textAlign: "left",
    lineHeight: 20,
  },
  underLineStyle: {
    borderBottomWidth: 2,
    borderBottomColor: Constants.APP_SEPARATOR_COLOR,
    // marginVertical: 5,
  },
  cardWrapper: {
    marginTop: 8,
    backgroundColor: Constants.APP_WHITE_COLOR,
  },
  deliveryText: {
    fontSize: 12,
    fontFamily: Constants.Fonts.MEDIUM,
    color: Constants.APP_GRAY_COLOR,
    textAlign: "left",
    marginLeft: 130,
    marginTop: 10,
    marginRight: 10,
  },
  deliverDateText: {
    fontSize: 12,
    fontFamily: Constants.Fonts.MEDIUM,
    color: Constants.APP_GRAY_COLOR,
    textAlign: "center",
  },
  refundableText: {
    fontSize: 12,
    fontFamily: Constants.Fonts.MEDIUM,
    color: Constants.APP_BLACK_COLOR,
    textAlign: "center",
  },
  deliverTimeText: {
    fontSize: 12,
    fontFamily: Constants.Fonts.MEDIUM,
    color: Constants.APP_GRAY_COLOR,
    textAlign: "right",
  },
  deliverTimeContainer: {
    marginTop: 10,
    marginRight: 14,
  },
  deliverDateContainer: {
    marginTop: 10,
    marginLeft: 25,
  },
  refundableContainer: {
    marginTop: 10,
    marginRight: 55,
  },
  categoryBottomContainer: {
    // alignItem: "center",
    justifyContent: "center",
    marginTop: 20,
  },
  buttonOutlineContainer: {
    width: "80%",
    alignSelf: "center",
    marginVertical: 10,
    marginHorizontal: 18,
    borderRadius: normalizedHeight(54 / 2),
    height: normalizedHeight(54),
    backgroundColor: Constants.APP_THEME_COLOR,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 25,
  },
  updateText: {
    fontFamily: Constants.Fonts.MEDIUM,
    fontSize: 15,
    color: Constants.APP_WHITE_COLOR,
  },
  titleStyle: {
    // marginTop: 20,
    textAlign: "left",
    marginLeft: 20,
    // marginBottom: 10,
    fontSize: 18,
    color: Constants.APP_THEME_COLOR,
    fontFamily: Constants.Fonts.MEDIUM,
  },
  selectedBalloonContainer: {
    marginHorizontal: 20,
    flexDirection: "row",
    marginVertical: 20,
    backgroundColor: Constants.APP_WHITE_COLOR,
    justifyContent: "center",
    // alignItems: 'flex-end'
  },
  balloonImg2: {
    height: 45,
    width: 45,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: constants.APP_SEPARATOR_COLOR,
    justifyContent: "center",
    alignItems: "center",
  },
  messageText2: {
    fontFamily: constants.Fonts.REGULAR,
    fontSize: 12,
    textAlign: "left",
    color: constants.APP_BLACK_COLOR,
    // lineHeight: 24,
    flex: 1,
    marginHorizontal: 15,
  },
  priceText1: {
    fontFamily: constants.Fonts.REGULAR,
    fontSize: 12,
    textAlign: "left",
    color: constants.APP_GRAY_COLOR,
    lineHeight: 24,
    flex: 1,
    marginHorizontal: 15,
    marginTop: 5,
    marginBottom: 10,
    // height: 50
  },
  priceText2: {
    fontFamily: constants.Fonts.REGULAR,
    fontSize: 12,
    textAlign: "left",
    color: constants.APP_BLACK_COLOR,
    // lineHeight: 24,
    flex: 1,
    marginHorizontal: 15,
  },
  productImgWrap: {
    borderRadius: 5,
    height: 45,
    width: 45,
    justifyContent: "center",
    borderWidth: 0.25,
    borderColor: constants.APP_GRAY_COLOR4,
    backgroundColor: constants.APP_WHITE_COLOR,
    // shadowColor: "#000",
    padding: 10,
    // shadowOffset: {
    //   width: 0,
    //   height: 1,
    // },
    // shadowOpacity: 0.22,
    // shadowRadius: 2.22,
    marginLeft: 10,
  },
  productImg: {
    height: "100%",
    width: "100%",
    resizeMode: "contain",
  },
  messageTitle: {
    fontFamily: Constants.Fonts.REGULAR,
    fontSize: 12,
    color: Constants.APP_BLACK_COLOR,
  },
  messageText: {
    flex: 1,
    fontFamily: Constants.Fonts.REGULAR,
    fontSize: 12,
    color: "rgb(109,109,109)",
    marginRight: 20,
    lineHeight: 20,
  },
});

export default styles;
